version: '3'
services:
  postgres:
    container_name: ecommerce
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fullstack
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres